name: Tests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-20.04, macos-15, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{matrix.python-version}}"
      - run: pip install tox tox-gh-actions
      - run: python -m tox
      # v4-beta is used instead of v3 because it supports "global upload token"
      # which is easier to use than having a separate token per repository
      - uses: codecov/codecov-action@v4.0.0-beta.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./tests/coverage.xml
