name: Tests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-20.04, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{matrix.python-version}}"
      - run: pip install -U pip
      - run: pip install tox tox-gh-actions
      - run: python -m tox
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./tests/coverage.xml
